package modelconfig

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

type Profile struct {
	VarName            string                 `json:"var_name"`
	Type               string                 `json:"type"`
	Name               string                 `json:"name"`
	APIBase            string                 `json:"apibase"`
	Model              string                 `json:"model"`
	APIKey             string                 `json:"apikey"`
	Stream             *bool                  `json:"stream,omitempty"`
	MaxRetries         *int                   `json:"max_retries,omitempty"`
	ReadTimeout        *int                   `json:"read_timeout,omitempty"`
	ConnectTimeout     *int                   `json:"connect_timeout,omitempty"`
	UserAgent          string                 `json:"user_agent,omitempty"`
	APIMode            string                 `json:"api_mode,omitempty"`
	ThinkingType       string                 `json:"thinking_type,omitempty"`
	ReasoningEffort    string                 `json:"reasoning_effort,omitempty"`
	FakeCCSystemPrompt string                 `json:"fake_cc_system_prompt,omitempty"`
	Extra              map[string]interface{} `json:"extra,omitempty"`
}

type Draft struct {
	UpdatedAt string    `json:"updated_at,omitempty"`
	Profiles  []Profile `json:"profiles"`
}
type Store struct{ Root string }

var nameRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func NewStore(root string) *Store { return &Store{Root: root} }
func (s *Store) path() string     { return filepath.Join(s.Root, "model_profiles.json") }

func Defaults() []Profile {
	b := true
	mr := 3
	rt := 300
	return []Profile{{VarName: "api_config_main", Type: "openai", Name: "main", APIBase: "https://api.openai.com/v1", Model: "gpt-4.1", Stream: &b, MaxRetries: &mr, ReadTimeout: &rt, Extra: map[string]interface{}{}}}
}

func (s *Store) Load(raw bool) (Draft, error) {
	data, err := os.ReadFile(s.path())
	if err != nil {
		d := Draft{Profiles: Defaults()}
		return d, nil
	}
	var d Draft
	if err := json.Unmarshal(data, &d); err != nil {
		return d, err
	}
	if len(d.Profiles) == 0 {
		d.Profiles = Defaults()
	}
	if !raw {
		for i := range d.Profiles {
			if d.Profiles[i].APIKey != "" {
				d.Profiles[i].APIKey = "******"
			}
		}
	}
	return d, nil
}

func (s *Store) Save(profiles []Profile) (Draft, error) {
	if err := Validate(profiles); err != nil {
		return Draft{}, err
	}
	d := Draft{UpdatedAt: time.Now().Format(time.RFC3339), Profiles: profiles}
	data, err := json.MarshalIndent(d, "", "  ")
	if err != nil {
		return d, err
	}
	return d, os.WriteFile(s.path(), data, 0600)
}

func Validate(profiles []Profile) error {
	seen := map[string]bool{}
	for _, p := range profiles {
		if p.VarName == "" || !nameRe.MatchString(p.VarName) {
			return fmt.Errorf("invalid var_name: %s", p.VarName)
		}
		if !strings.Contains(strings.ToLower(p.VarName), "api") && !strings.Contains(strings.ToLower(p.VarName), "config") && !strings.Contains(strings.ToLower(p.VarName), "cookie") {
			return fmt.Errorf("var_name must contain api/config/cookie: %s", p.VarName)
		}
		if seen[p.VarName] {
			return fmt.Errorf("duplicate var_name: %s", p.VarName)
		}
		seen[p.VarName] = true
		if p.Name == "" || p.APIBase == "" || p.Model == "" {
			return errors.New("name, apibase and model are required")
		}
	}
	return nil
}

func SourceStatus(gaRoot string) map[string]interface{} {
	mykey := filepath.Join(gaRoot, "mykey.py")
	jsonp := filepath.Join(gaRoot, "mykey.json")
	gen := filepath.Join(gaRoot, "mykey_admin.generated.py")
	return map[string]interface{}{
		"mykey_py_exists": exists(mykey), "mykey_json_exists": exists(jsonp), "generated_exists": exists(gen), "generated_path": gen,
		"safe_note": "Existing mykey.py is never read or overwritten by this admin UI.",
	}
}
func exists(p string) bool { st, err := os.Stat(p); return err == nil && !st.IsDir() }

func Render(profiles []Profile) (string, error) {
	if err := Validate(profiles); err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# Auto-generated by GenericAgent-Admin-Go.\n# Review before copying to mykey.py. Keep this file private.\n# GA discovers variables whose names contain api/config/cookie.\n\n")
	for _, p := range profiles {
		m := map[string]interface{}{}
		m["name"] = p.Name
		m["apikey"] = p.APIKey
		m["apibase"] = p.APIBase
		m["model"] = p.Model
		if p.Stream != nil {
			m["stream"] = *p.Stream
		}
		if p.MaxRetries != nil {
			m["max_retries"] = *p.MaxRetries
		}
		if p.ReadTimeout != nil {
			m["read_timeout"] = *p.ReadTimeout
		}
		if p.ConnectTimeout != nil {
			m["connect_timeout"] = *p.ConnectTimeout
		}
		if p.UserAgent != "" {
			m["user_agent"] = p.UserAgent
		}
		if p.APIMode != "" {
			m["api_mode"] = p.APIMode
		}
		if p.ThinkingType != "" {
			m["thinking_type"] = p.ThinkingType
		}
		if p.ReasoningEffort != "" {
			m["reasoning_effort"] = p.ReasoningEffort
		}
		if p.FakeCCSystemPrompt != "" {
			m["fake_cc_system_prompt"] = p.FakeCCSystemPrompt
		}
		for k, v := range p.Extra {
			if _, ok := m[k]; !ok {
				m[k] = v
			}
		}
		b.WriteString(fmt.Sprintf("%s = %s\n\n", p.VarName, pyDict(m)))
	}
	return b.String(), nil
}

func pyDict(m map[string]interface{}) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	parts := []string{}
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("%q: %s", k, pyVal(m[k])))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}
func pyVal(v interface{}) string {
	switch x := v.(type) {
	case string:
		return fmt.Sprintf("%q", x)
	case bool:
		if x {
			return "True"
		}
		return "False"
	case float64:
		return fmt.Sprintf("%v", x)
	case int:
		return fmt.Sprintf("%d", x)
	case nil:
		return "None"
	default:
		data, _ := json.Marshal(x)
		return string(data)
	}
}

func Export(gaRoot string, profiles []Profile, activateIfSafe bool) (map[string]interface{}, error) {
	text, err := Render(profiles)
	if err != nil {
		return nil, err
	}
	gen := filepath.Join(gaRoot, "mykey_admin.generated.py")
	if err := os.WriteFile(gen, []byte(text), 0600); err != nil {
		return nil, err
	}
	res := map[string]interface{}{"generated_path": gen, "activated": false, "active_path": nil}
	active := filepath.Join(gaRoot, "mykey.py")
	if activateIfSafe && !exists(active) {
		if err := os.WriteFile(active, []byte(text), 0600); err != nil {
			return nil, err
		}
		res["activated"] = true
		res["active_path"] = active
	}
	return res, nil
}
