import { useState } from 'react'
import { Eye, RefreshCw, Search, UploadCloud } from 'lucide-react'
import { api } from '../lib/api'
import { emptyProfile } from '../lib/format'
import { Panel, SecretInput } from '../components/common'

export function Models({ t, profiles, setProfiles, patchProfile, importModels, previewModels, saveModels, modelPreview }) {
  const [q, setQ] = useState('')
  const shown = q ? profiles.filter(p => [p.name, p.var_name, p.model].some(f => (f || '').toLowerCase().includes(q.toLowerCase()))) : profiles
  return <section><div className="model-top"><div><h3>{t.nav.models}</h3><p>{t.hints.previewHelp}</p></div><div className="actions"><button onClick={importModels}><RefreshCw size={14}/>{t.hints.modelSource}</button><button onClick={() => setProfiles([...profiles, emptyProfile(profiles.length)])}>{t.hints.addProfile}</button><button onClick={previewModels}><Eye size={14}/>{t.hints.preview}</button><button onClick={saveModels}><UploadCloud size={14}/>{t.hints.writeMykey}</button></div></div><div className="search-bar"><Search size={14}/><input placeholder={t.search || 'Search profiles…'} value={q} onChange={e => setQ(e.target.value)} style={{border:'none',outline:'none',flex:1}}/>{q && <button onClick={() => setQ('')} style={{padding:'0 4px',fontSize:11}}>✕</button>}{shown.length !== profiles.length && <small className="muted">{shown.length}/{profiles.length}</small>}</div><div className="models-layout"><div className="profiles">{shown.map((p, idx) => {
    const realIdx = profiles.indexOf(p)
    return <div className="profile" key={realIdx}><div className="profile-head"><b>#{realIdx + 1} {p.name || p.var_name}</b><label><input type="checkbox" checked={!!p.enabled} onChange={(e) => patchProfile(realIdx, { enabled: e.target.checked })}/> enabled</label></div><div className="form-grid"><label>{t.fields.varName}<input value={p.var_name || ''} onChange={(e) => patchProfile(realIdx, { var_name: e.target.value })}/></label><label>{t.fields.type}<input value={p.type || ''} onChange={(e) => patchProfile(realIdx, { type: e.target.value })}/></label><label>{t.fields.name}<input value={p.name || ''} onChange={(e) => patchProfile(realIdx, { name: e.target.value })}/></label><label>{t.fields.model}<input value={p.model || ''} onChange={(e) => patchProfile(realIdx, { model: e.target.value })}/></label><label className="span2">{t.fields.apiBase}<input value={p.apibase || ''} onChange={(e) => patchProfile(realIdx, { apibase: e.target.value })}/></label><label className="span2">{t.fields.apiKey}<SecretInput value={p.apikey} onChange={(v) => patchProfile(realIdx, { apikey: v })} t={t}/></label><label>{t.fields.stream}<select value={String(!!p.stream)} onChange={(e) => patchProfile(realIdx, { stream: e.target.value === 'true' })}><option value="true">true</option><option value="false">false</option></select></label><label>{t.fields.maxRetries}<input type="number" value={p.max_retries ?? 3} onChange={(e) => patchProfile(realIdx, { max_retries: Number(e.target.value) })}/></label><label>{t.fields.readTimeout}<input type="number" value={p.read_timeout ?? 300} onChange={(e) => patchProfile(realIdx, { read_timeout: Number(e.target.value) })}/></label><label>{t.fields.reasoningEffort}<input value={p.reasoning_effort || ''} onChange={(e) => patchProfile(realIdx, { reasoning_effort: e.target.value })}/></label></div></div>
  })}</div><Panel title={t.lists.generatedPreview} className="preview"><pre>{modelPreview || t.empty}</pre></Panel></div></section>
}
