import { useEffect, useMemo, useState } from 'react'
import { Activity, Bot, Brain, CalendarClock, CheckCircle2, Eye, FileCode2, FolderCog, Globe2, MessageSquare, Play, RefreshCw, Save, Search, Server, ShieldAlert, SlidersHorizontal, Square, Terminal, UploadCloud, XCircle } from 'lucide-react'

const api = async (url, options = {}) => {
  const res = await fetch(url, { headers: { 'Content-Type': 'application/json' }, ...options })
  const text = await res.text()
  let body = null
  try { body = text ? JSON.parse(text) : null } catch { throw new Error(`Expected JSON from ${url}, got ${text.slice(0, 40)}`) }
  if (!res.ok) throw new Error(body?.detail || `${res.status} ${res.statusText}`)
  return body
}

const I18N = {
  zh: {
    appName: 'GA Admin', tagline: 'GenericAgent 生命周期控制面', root: 'GenericAgent 根目录', setupTitle: '首次配置 GenericAgent', setupDesc: '请选择已有 GA 根目录，或一键安装到新目录。', validateRoot: '验证并使用', installGA: '安装 GA', installPath: '安装目录', setupOk: 'GA 路径已配置', installDone: 'GA 已安装并配置', browse: '选择目录', checkEnv: '检查 Python / Git', envReady: '环境已就绪', envMissing: '环境缺失', save: '保存', refresh: '刷新', busy: '执行中', ready: '就绪', error: '错误', empty: '暂无', enabled: '启用', disabled: '停用', start: '启动', stop: '停止', running: '运行中', stopped: '已停止', language: '语言', show: '显示', hide: '隐藏', search: '搜索', read: '读取', create: '创建', remove: '删除', backup: '写操作会自动备份',
    nav: { overview: '总览', chat: '对话', control: '控制面', files: '文件', tasks: '任务', memory: '记忆', channels: '通道', autonomous: '自主进化', schedule: '定时', models: '模型', logs: '日志' },
    desc: { overview: '从 GA 的功能域理解并接管生命周期。', chat: '迁移自 reactapp 的 GA 原生对话、文件上传和流式聊天界面。', control: '运行前检查、能力地图、风险摘要与最近报告。', files: '安全浏览 GA 根目录内文本文件，支持 tail 与搜索。', tasks: '普通会话、任务文件、批处理入口与任务型服务。', memory: '分层记忆、SOP 与工具能力索引。', channels: '桌面、TUI、Web、IM Bot 等前端入口。', autonomous: '反思、自主运行、Goal Mode 与团队 Worker。', schedule: 'sche_tasks JSON 定时任务详情、编辑、创建与删除。', models: '读取/预览/写回 GA mykey.py 模型配置。', logs: '进程状态与输出日志。' },
    cards: { processes: '进程', running: '运行中', stopped: '已停止', memoryLayers: '记忆层', sopTools: 'SOP/工具', schedule: '定时任务', enabledTasks: '已启用', reports: '报告', coreFiles: '核心文件', channels: '通道文件', reflect: '反思脚本', health: 'GA 健康', capabilities: '能力', risks: '风险' },
    lists: { serviceGroups: '服务域', coreFiles: '核心文件', reflect: 'Reflect / Autonomous', frontends: '前端 / 通道', memory: '记忆层级', sop: 'SOP 与工具', taskServices: '任务服务', frontendServices: '前端服务', reflectServices: '反思服务', discoveredChannels: '发现的通道文件', reflectScripts: '反思脚本', scheduledTasks: '定时任务', recentReports: '最近报告', processes: '进程', generatedPreview: '生成预览', riskHints: '接管提示', capabilities: '能力地图', readiness: '运行前检查', fileList: '文件列表', filePreview: '文件预览', searchResults: '搜索结果', editor: '编辑器' },
    hints: { rootSaved: 'GA 根目录已保存', taskSaved: '任务已保存并备份旧文件', taskDeleted: '任务已删除并备份', taskToggled: '任务状态已更新', modelsSaved: 'mykey.py 已备份并写回', savedSecret: '已保存；输入新值可替换', secret: 'API Key / Token', noFrontend: '未发现前端服务', noReflect: '未发现 reflect 服务', noTasks: '暂无 sche_tasks/*.json', noLogs: '暂无日志', previewHelp: '点击“预览”查看配置；点击“写回 mykey.py”会先备份再覆盖 GA 的 mykey.py。', modelSource: '来源', secretHidden: '已隐藏真实密钥', addProfile: '新增 Profile', preview: '预览', writeMykey: '写回 mykey.py', filePath: '相对路径', searchText: '搜索文本', tailLines: '尾部行数', newTaskId: 'new_task', jsonHelp: 'JSON 需为对象；保存/删除会生成 .bak 时间戳。' },
    fields: { varName: '变量名', type: '类型', name: '名称', model: '模型', apiBase: 'API Base', apiKey: 'API Key', stream: '流式', maxRetries: '重试', readTimeout: '超时', reasoningEffort: '推理强度', editor: 'JSON 内容' }
  },
  en: {
    appName: 'GA Admin', tagline: 'GenericAgent lifecycle control plane', root: 'GenericAgent root', setupTitle: 'First-time GenericAgent setup', setupDesc: 'Select an existing GA root, or install GA into a new directory.', validateRoot: 'Validate & use', installGA: 'Install GA', installPath: 'Install path', setupOk: 'GA root configured', installDone: 'GA installed and configured', browse: 'Choose directory', checkEnv: 'Check Python / Git', envReady: 'Environment ready', envMissing: 'Environment missing', save: 'Save', refresh: 'Refresh', busy: 'Busy', ready: 'Ready', error: 'Error', empty: 'Empty', enabled: 'Enabled', disabled: 'Disabled', start: 'Start', stop: 'Stop', running: 'Running', stopped: 'Stopped', language: 'Language', show: 'Show', hide: 'Hide', search: 'Search', read: 'Read', create: 'Create', remove: 'Delete', backup: 'writes create backups',
    nav: { overview: 'Overview', chat: 'Chat', control: 'Control', files: 'Files', tasks: 'Tasks', memory: 'Memory', channels: 'Channels', autonomous: 'Autonomous', schedule: 'Schedule', models: 'Models', logs: 'Logs' },
    desc: { overview: 'Understand and take over GA lifecycle by native domains.', chat: 'GA native conversation, uploads and streaming UI migrated from reactapp.', control: 'Readiness, capability map, risks and recent reports.', files: 'Safely browse text files inside GA root with tail and search.', tasks: 'Conversations, task files, batch entrypoints and task services.', memory: 'Layered memory, SOPs and utility indexes.', channels: 'Desktop, TUI, Web and IM Bot entrypoints.', autonomous: 'Reflection, autonomous runs, Goal Mode and team workers.', schedule: 'View, edit, create and delete sche_tasks JSON jobs.', models: 'Import, preview and write GA mykey.py model config.', logs: 'Process state and output logs.' },
    cards: { processes: 'Processes', running: 'Running', stopped: 'Stopped', memoryLayers: 'Memory layers', sopTools: 'SOP/tools', schedule: 'Scheduled jobs', enabledTasks: 'Enabled', reports: 'Reports', coreFiles: 'Core files', channels: 'Channels', reflect: 'Reflect scripts', health: 'GA health', capabilities: 'Capabilities', risks: 'Risks' },
    lists: { serviceGroups: 'Service domains', coreFiles: 'Core files', reflect: 'Reflect / Autonomous', frontends: 'Frontends / Channels', memory: 'Memory layers', sop: 'SOPs and tools', taskServices: 'Task services', frontendServices: 'Frontend services', reflectServices: 'Reflect services', discoveredChannels: 'Discovered channels', reflectScripts: 'Reflect scripts', scheduledTasks: 'Scheduled jobs', recentReports: 'Recent reports', processes: 'Processes', generatedPreview: 'Generated preview', riskHints: 'Takeover hints', capabilities: 'Capability map', readiness: 'Readiness', fileList: 'Files', filePreview: 'Preview', searchResults: 'Search results', editor: 'Editor' },
    hints: { rootSaved: 'GA root saved', taskSaved: 'Task saved with backup', taskDeleted: 'Task deleted with backup', taskToggled: 'Task state updated', modelsSaved: 'mykey.py backed up and written', savedSecret: 'Saved; type a new value to replace', secret: 'API Key / Token', noFrontend: 'No frontend service found', noReflect: 'No reflect service found', noTasks: 'No sche_tasks/*.json', noLogs: 'No logs', previewHelp: 'Preview generated config; writing mykey.py backs up first.', modelSource: 'Source', secretHidden: 'Real secret hidden', addProfile: 'Add profile', preview: 'Preview', writeMykey: 'Write mykey.py', filePath: 'relative path', searchText: 'search text', tailLines: 'tail lines', newTaskId: 'new_task', jsonHelp: 'JSON must be an object; save/delete creates timestamped .bak.' },
    fields: { varName: 'Var name', type: 'Type', name: 'Name', model: 'Model', apiBase: 'API Base', apiKey: 'API Key', stream: 'Stream', maxRetries: 'Retries', readTimeout: 'Timeout', reasoningEffort: 'Reasoning effort', editor: 'JSON content' }
  }
}

const emptyProfile = (idx = 0) => ({ var_name: `MODEL_${idx + 1}`, type: 'openai', name: '', model: '', apibase: '', apikey: '', stream: true, max_retries: 3, read_timeout: 300, reasoning_effort: '', enabled: true })
const safeJson = (v) => JSON.stringify(v ?? {}, null, 2)
const group = (items, pred) => (items || []).filter(pred)

function Stat({ label, value, icon }) { return <div className="stat"><div>{icon}</div><span>{label}</span><b>{value}</b></div> }
function Panel({ title, children, className = '' }) { return <div className={`panel ${className}`}><div className="panel-title">{title}</div>{children}</div> }
function EntryList({ items = [], empty }) { return <div className="entry-list">{items.length ? items.map((e, i) => <div className="entry" key={`${e.path || e.name}-${i}`}><b>{e.name || e.path}</b><span>{e.path}{e.kind ? ` · ${e.kind}` : ''}{e.size ? ` · ${e.size} B` : ''}</span></div>) : <p className="muted">{empty}</p>}</div> }
function ServiceRow({ svc, onStart, onStop, onLogs, t }) { return <div className="service-card"><div><b>{svc.name}</b><span title={svc.command?.join(' ')}>{svc.command?.join(' ')}</span><em>{svc.kind}{svc.pid ? ` · PID ${svc.pid}` : ''}</em></div><div className={svc.running ? 'ok' : 'err'}>{svc.running ? t.running : t.stopped}</div><div className="svc-actions"><button disabled={svc.running} onClick={() => onStart(svc.name)}><Play size={14}/>{t.start}</button><button disabled={!svc.running} onClick={() => onStop(svc.name)}><Square size={14}/>{t.stop}</button><button onClick={() => onLogs?.(svc.name)}><Eye size={14}/>{t.logs}</button></div></div> }
function SecretInput({ value, onChange, t }) { const [show, setShow] = useState(false); return <div className="secret-row"><input type={show ? 'text' : 'password'} value={value || ''} placeholder={t.hints.savedSecret} onChange={e => onChange(e.target.value)} /><button type="button" onClick={() => setShow(!show)}>{show ? t.hide : t.show}</button></div> }

export default function App() {
  const defaultLang = (navigator.language || '').toLowerCase().startsWith('zh') ? 'zh' : 'en'
  const [lang, setLang] = useState(localStorage.getItem('ga-admin-lang') || defaultLang)
  const t = I18N[lang] || I18N.en
  const [tab, setTab] = useState('overview')
  const [cfg, setCfg] = useState(null), [health, setHealth] = useState(null), [control, setControl] = useState(null), [services, setServices] = useState([]), [logs, setLogs] = useState([])
  const [root, setRoot] = useState(''), [installRoot, setInstallRoot] = useState(''), [busy, setBusy] = useState(false), [msg, setMsg] = useState(''), [selected, setSelected] = useState('')
  const [setupEnv, setSetupEnv] = useState(null)
  const [profiles, setProfiles] = useState([]), [modelPreview, setModelPreview] = useState('')
  const [filePath, setFilePath] = useState('memory'), [fileList, setFileList] = useState([]), [fileContent, setFileContent] = useState(''), [fileSearch, setFileSearch] = useState(''), [searchHits, setSearchHits] = useState([]), [tailLines, setTailLines] = useState(200)
  const [taskId, setTaskId] = useState(''), [taskEditor, setTaskEditor] = useState('{}'), [newTaskId, setNewTaskId] = useState('new_task')
  const [scheduleArtifactTitle, setScheduleArtifactTitle] = useState(''), [scheduleArtifact, setScheduleArtifact] = useState('')

  const inv = health?.inventory || {}
  const schedule = inv.schedule || {}
  const tasks = schedule.tasks || []
  const taskSvcs = useMemo(() => group(services, s => s.kind === 'task' || s.name?.includes('task')), [services])
  const frontendSvcs = useMemo(() => group(services, s => s.kind === 'frontend'), [services])
  const reflectSvcs = useMemo(() => group(services, s => s.kind === 'reflect' || s.name?.includes('reflect') || s.name?.includes('autonomous')), [services])

  const load = async () => {
    setBusy(true); setMsg('')
    try {
      const [c, h] = await Promise.all([api('/api/config'), api('/api/ga/health')])
      setCfg(c); setRoot(c.ga_root || ''); setHealth(h)
      if (!h?.ok) {
        setServices([]); setControl(null); setLogs([]); setFileList([])
        return
      }
      const [svc, ctrl] = await Promise.all([api('/api/services'), api('/api/ga/control')])
      const serviceList = Array.isArray(svc) ? svc : (svc.services || [])
      setServices(serviceList); setControl(ctrl)
      const first = serviceList[0]?.name; if (!selected && first) setSelected(first)
      await loadFiles(filePath)
    } catch (e) { setMsg(e.message) } finally { setBusy(false) }
  }
  useEffect(() => { load() }, [])
  useEffect(() => { localStorage.setItem('ga-admin-lang', lang) }, [lang])
  useEffect(() => { if (selected) api(`/api/logs/${encodeURIComponent(selected)}`).then(d => setLogs(d.lines || [])).catch(e => setMsg(e.message)) }, [selected])

  const saveConfig = async () => { setBusy(true); try { const c = await api('/api/config', { method: 'PUT', body: JSON.stringify({ ...cfg, ga_root: root }) }); setCfg(c); setMsg(t.hints.rootSaved); await load() } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const checkSetupEnv = async () => { setBusy(true); try { const d = await api('/api/setup/env'); setSetupEnv(d); setMsg(d.ok ? t.envReady : t.envMissing) } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const browseSetupDir = async (target = 'root') => { setBusy(true); try { const base = target === 'install' ? installRoot : root; const d = await api('/api/setup/browse', { method:'POST', body: JSON.stringify({ path: base }) }); if (d.path) { target === 'install' ? setInstallRoot(d.path) : setRoot(d.path) } } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const validateSetupRoot = async () => { setBusy(true); try { const d = await api('/api/setup/validate', { method:'POST', body: JSON.stringify({ path: root }) }); if (!d.ok) throw new Error('GenericAgent health check failed'); const c = await api('/api/config', { method:'PUT', body: JSON.stringify({ ...cfg, ga_root: d.root }) }); setCfg(c); setRoot(d.root); setMsg(t.setupOk); await load() } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const installGA = async () => { setBusy(true); try { const env = setupEnv || await api('/api/setup/env'); setSetupEnv(env); if (!env.ok) throw new Error(t.envMissing); const d = await api('/api/setup/install', { method:'POST', body: JSON.stringify({ path: installRoot || root }) }); setRoot(d.root); setMsg(t.installDone); await load() } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const serviceAction = async (name, action) => { setBusy(true); try { await api(`/api/services/${action}`, { method:'POST', body: JSON.stringify({ name }) }); await load(); if (selected === name) setLogs((await api(`/api/logs/${encodeURIComponent(name)}?lines=${tailLines}`)).lines || []) } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const loadServiceLogs = async (name = selected) => { if (!name) return; setSelected(name); setLogs((await api(`/api/logs/${encodeURIComponent(name)}?lines=${tailLines}`)).lines || []) }
  const viewServiceLogs = async (name) => { setTab('logs'); await loadServiceLogs(name) }
  const toggleTask = async (id, enabled) => { setBusy(true); try { await api('/api/schedule/toggle', { method:'POST', body: JSON.stringify({ id, enabled }) }); setMsg(t.hints.taskToggled); await load() } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }

  const loadFiles = async (path = '') => { const d = await api(`/api/files/list?path=${encodeURIComponent(path || '')}`); setFileList(d.items || d.entries || []); setFilePath(path || '') }
  const readFile = async (path = filePath) => { setBusy(true); try { const d = await api(`/api/files/read?path=${encodeURIComponent(path)}`); setFileContent(d.content || ''); setFilePath(path); setTab('files') } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const tailFile = async (path = filePath) => { if (!path) return; setBusy(true); try { const d = await api(`/api/files/tail?path=${encodeURIComponent(path)}&lines=${tailLines}`); setFileContent(d.content || ''); setFilePath(path); setTab('files') } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const saveFile = async () => { if (!filePath) return; setBusy(true); try { const d = await api('/api/files/write', { method:'POST', body: JSON.stringify({ path:filePath, content:fileContent }) }); setFileContent(d.content || fileContent); setMsg(t.hints.fileSaved || t.saved || 'Saved'); await loadFiles(filePath.includes('/') ? filePath.split('/').slice(0,-1).join('/') : '') } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const runSearch = async () => { setBusy(true); try { const d = await api(`/api/files/search?path=${encodeURIComponent(filePath)}&q=${encodeURIComponent(fileSearch)}&limit=80`); setSearchHits(d.hits || []) } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }

  const loadTask = async (id) => { setBusy(true); try { const d = await api(`/api/schedule/task?id=${encodeURIComponent(id)}`); setTaskId(d.id || id); setTaskEditor(safeJson(d.raw)); setTab('schedule') } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const saveTask = async () => { setBusy(true); try { await api('/api/schedule/task', { method:'PUT', body: JSON.stringify({ id: taskId || newTaskId, raw: JSON.parse(taskEditor) }) }); setMsg(t.hints.taskSaved); await load() } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const createTask = async () => { setTaskId(newTaskId); setTaskEditor(safeJson({ schedule: '09:00', repeat: 'daily', enabled: false, prompt: '' })) }
  const deleteTask = async () => { if (!taskId) return; setBusy(true); try { await api('/api/schedule/delete', { method:'POST', body: JSON.stringify({ id: taskId }) }); setMsg(t.hints.taskDeleted); setTaskId(''); setTaskEditor('{}'); await load() } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const readScheduleArtifact = async (path, targetTab = 'schedule') => { setBusy(true); try { const d = await api(`/api/schedule/artifact?path=${encodeURIComponent(path)}`); setScheduleArtifactTitle(path); setScheduleArtifact(d.content || ''); setTab(targetTab) } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }

  const importModels = async () => { setBusy(true); try { const d = await api('/api/models/import-mykey', { method:'POST', body: JSON.stringify({ reveal:false, save:false }) }); setProfiles(d.profiles?.length ? d.profiles : [emptyProfile(0)]); setModelPreview(safeJson(d)) } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  useEffect(() => { if (tab === 'models' && profiles.length === 0) importModels() }, [tab])
  const previewModels = async () => { setBusy(true); try { const d = await api('/api/models/preview', { method:'POST', body: JSON.stringify({ profiles }) }); setModelPreview(d.python || safeJson(d)) } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const saveModels = async () => { setBusy(true); try { const d = await api('/api/models/export', { method:'POST', body: JSON.stringify({ profiles, overwrite_active:true }) }); setModelPreview(safeJson(d)); setMsg(t.hints.modelsSaved) } catch(e){ setMsg(e.message) } finally{ setBusy(false) } }
  const patchProfile = (idx, patch) => setProfiles(ps => ps.map((p, i) => i === idx ? { ...p, ...patch } : p))

  const nav = ['overview','chat','control','files','tasks','memory','channels','autonomous','schedule','models','logs']

  const needsSetup = !!health && !health?.ok
  if (needsSetup) return <div className="setup-shell"><div className="setup-card"><div className="brand setup-brand"><Bot/><div><h1>{t.setupTitle}</h1><p>{t.setupDesc}</p></div></div><div className="setup-env"><button className="secondary" onClick={checkSetupEnv} disabled={busy}>{t.checkEnv}</button>{setupEnv?.tools?.map(tool => <span key={tool.name} className={tool.ok ? 'ok' : 'err'} title={[tool.path, tool.version, tool.error].filter(Boolean).join('\n')}>{tool.ok ? '✓' : '×'} {tool.name}</span>)}</div><label>{t.root}<div className="setup-path-row"><input value={root} onChange={e=>setRoot(e.target.value)} placeholder="C:\\Users\\...\\GenericAgent"/><button className="secondary" onClick={()=>browseSetupDir('root')} disabled={busy}>{t.browse}</button></div></label><button onClick={validateSetupRoot} disabled={busy || !root}>{busy ? t.busy : t.validateRoot}</button><div className="setup-divider"><span>or</span></div><label>{t.installPath}<div className="setup-path-row"><input value={installRoot} onChange={e=>setInstallRoot(e.target.value)} placeholder="C:\\Users\\...\\GenericAgent"/><button className="secondary" onClick={()=>browseSetupDir('install')} disabled={busy}>{t.browse}</button></div></label><button className="secondary" onClick={installGA} disabled={busy || !(installRoot || root)}>{t.installGA}</button>{msg && <div className="message">{msg}</div>}<p className="setup-note">git clone https://github.com/lsdefine/GenericAgent</p></div></div>

  return <div className="app">
    <aside className="sidebar"><div className="brand"><Bot/><div><h1>{t.appName}</h1><p>{t.tagline}</p></div></div><div className="lang-switch"><Globe2 size={15}/>{t.language}<select value={lang} onChange={e=>setLang(e.target.value)}><option value="zh">中文</option><option value="en">English</option></select></div><div className="root-box"><label>{t.root}</label><div><input value={root} onChange={e=>setRoot(e.target.value)}/><button onClick={saveConfig}><Save size={14}/></button></div></div><nav>{nav.map(n => <button key={n} className={tab===n?'active':''} onClick={()=> n === 'chat' ? window.open('/chat', '_blank', 'noopener,noreferrer') : setTab(n)}>{icon(n)}{t.nav[n]}{n === 'chat' && <span className="nav-pop">open</span>}</button>)}</nav><button className="refresh" onClick={load} disabled={busy}><RefreshCw size={15}/>{busy ? t.busy : t.refresh}</button>{msg && <div className="message">{msg}</div>}</aside>
    <main className="main"><header><div><h2>{t.nav[tab]}</h2><p>{t.desc[tab]}</p></div><div className="badges"><span>{cfg?.host}:{cfg?.port}</span><span className={health?.ok?'ok':'err'}>{health?.ok ? t.ready : t.error}</span></div></header>
      {tab==='overview' && <section><div className="stats"><Stat label={t.cards.processes} value={services.length} icon={<Server/>}/><Stat label={t.cards.running} value={services.filter(s=>s.running).length} icon={<Activity/>}/><Stat label={t.cards.schedule} value={schedule.task_count || 0} icon={<CalendarClock/>}/><Stat label={t.cards.enabledTasks} value={schedule.enabled || 0} icon={<CheckCircle2/>}/></div><div className="grid2"><Panel title={t.lists.coreFiles}><EntryList items={inv.core_files || []} empty={t.empty}/></Panel><Panel title={t.lists.riskHints}><ul className="risk"><li>{t.root}: {root}</li><li>sche_tasks JSON: {t.backup}</li><li>mykey.py: {t.backup}</li></ul></Panel></div></section>}
      {tab==='chat' && <ChatPage t={t}/>}
      {tab==='control' && <section><div className="stats"><Stat label={t.cards.health} value={health?.ok ? 'OK' : 'FAIL'} icon={<ShieldAlert/>}/><Stat label={t.cards.capabilities} value={control?.capabilities?.length || 0} icon={<Brain/>}/><Stat label={t.cards.risks} value={control?.risks?.length || 0} icon={<ShieldAlert/>}/><Stat label={t.cards.reports} value={control?.reports?.length || 0} icon={<FileCode2/>}/></div><div className="grid2"><Panel title={t.lists.readiness}><EntryList items={(control?.readiness || []).map((r,i)=>({name:r.area, path:r.text, kind:r.level}))} empty="OK"/></Panel><Panel title={t.lists.capabilities}><EntryList items={(control?.capabilities || []).map(c=>({name:c.name,path:c.path,kind:c.kind}))} empty={t.empty}/></Panel><Panel title={t.lists.recentReports}><EntryList items={control?.reports || []} empty={t.empty}/></Panel><Panel title={t.lists.riskHints}><EntryList items={(control?.risks || []).map(r=>({name:r.area,path:r.text,kind:r.level}))} empty="OK"/></Panel></div></section>}
      {tab==='files' && <section><div className="workspace"><Panel title={t.lists.fileList}><div className="inline-form"><input value={filePath} onChange={e=>setFilePath(e.target.value)} placeholder={t.hints.filePath}/><button onClick={()=>loadFiles(filePath)}>{t.read}</button></div><div className="inline-form"><input value={fileSearch} onChange={e=>setFileSearch(e.target.value)} placeholder={t.hints.searchText}/><button onClick={runSearch}><Search size={14}/>{t.search}</button></div><div className="inline-form"><input type="number" value={tailLines} onChange={e=>setTailLines(Number(e.target.value))}/><span>{t.hints.tailLines}</span><button onClick={()=>tailFile(filePath)}>{t.tail || 'Tail'}</button><button onClick={saveFile} disabled={!filePath}><Save size={14}/>{t.save}</button></div><div className="file-list">{fileList.map(e=><button key={e.path} onClick={()=> e.kind==='dir' ? loadFiles(e.path) : readFile(e.path)}>{e.kind==='dir'?'📁':'📄'} {e.path}</button>)}</div><h4>{t.lists.searchResults}</h4>{searchHits.map(h=><button className="hit" key={`${h.path}:${h.line}`} onClick={()=>readFile(h.path)}>{h.path}:{h.line} · {h.preview}</button>)}</Panel><Panel title={t.lists.filePreview} className="log-panel"><textarea className="file-editor" value={fileContent} onChange={e=>setFileContent(e.target.value)} placeholder={t.empty}/></Panel></div></section>}
      {tab==='tasks' && <section><div className="grid2"><Panel title={t.lists.taskServices}>{taskSvcs.length ? taskSvcs.map(s=><ServiceRow key={s.name} svc={s} t={t} onStart={n=>serviceAction(n,'start')} onStop={n=>serviceAction(n,'stop')} onLogs={viewServiceLogs}/>) : <EntryList items={tasks.map(task=>({name:task.id,path:`${task.schedule} · ${task.repeat} · ${task.status}`,kind:task.enabled ? t.enabled : t.disabled}))} empty={t.hints.noTasks}/>}</Panel><Panel title={t.lists.scheduledTasks}>{tasks.length ? tasks.map(task=><TaskRow key={task.id} task={task} t={t} onToggle={toggleTask} onEdit={loadTask}/>) : <p className="muted">{t.hints.noTasks}</p>}</Panel></div></section>}
      {tab==='memory' && <section><div className="grid2"><Panel title={t.lists.memory}><EntryList items={[inv.memory?.insight, inv.memory?.facts].filter(Boolean)} empty={t.empty}/></Panel><Panel title={t.lists.sop}><EntryList items={[...(inv.memory?.sops||[]), ...(inv.memory?.utils||[])]} empty={t.empty}/></Panel></div></section>}
      {tab==='channels' && <section><div className="grid2"><Panel title={t.lists.frontendServices}>{frontendSvcs.map(s=><ServiceRow key={s.name} svc={s} t={t} onStart={n=>serviceAction(n,'start')} onStop={n=>serviceAction(n,'stop')} onLogs={viewServiceLogs}/>)}</Panel><Panel title={t.lists.discoveredChannels}><EntryList items={inv.frontends || []} empty={t.hints.noFrontend}/></Panel></div></section>}
      {tab==='autonomous' && <section><div className="grid2"><Panel title={t.lists.reflectServices}>{reflectSvcs.length ? reflectSvcs.map(s=><ServiceRow key={s.name} svc={s} t={t} onStart={n=>serviceAction(n,'start')} onStop={n=>serviceAction(n,'stop')} onLogs={viewServiceLogs}/>) : <p className="muted">{t.hints.noReflect}</p>}</Panel><Panel title={t.lists.reflectScripts}><EntryList items={inv.reflect || []} empty={t.hints.noReflect}/></Panel></div><Panel title={t.lists.recentReports}><div className="report-list">{(inv.autonomous_reports || []).map(r=><button key={r.path} onClick={()=>readScheduleArtifact(r.path, 'autonomous')}>{r.name}<small>{new Date(r.mod_time).toLocaleString()}</small></button>)}</div><pre className="artifact-view">{scheduleArtifactTitle?.includes('autonomous_reports') ? (scheduleArtifact || t.empty) : t.empty}</pre></Panel></section>}
      {tab==='schedule' && <section><div className="stats schedule-stats"><div className="stat"><CalendarClock/><span>{t.enabled}</span><b>{schedule.enabled || 0}</b></div><div className="stat"><XCircle/><span>Overdue</span><b>{schedule.overdue || 0}</b></div><div className="stat"><FolderCog/><span>Reports</span><b>{schedule.done_count || 0}</b></div><div className="stat"><ShieldAlert/><span>Errors</span><b>{schedule.errors || 0}</b></div></div><div className="workspace"><Panel title={t.lists.scheduledTasks}><div className="inline-form"><input value={newTaskId} onChange={e=>setNewTaskId(e.target.value)} placeholder={t.hints.newTaskId}/><button onClick={createTask}>{t.create}</button>{schedule.log?.exists && <button onClick={()=>readScheduleArtifact('sche_tasks/scheduler.log')}>{t.nav.logs}</button>}</div>{tasks.map(task=><TaskRow key={task.id} task={task} t={t} onToggle={toggleTask} onEdit={loadTask} onArtifact={readScheduleArtifact}/>)}</Panel><Panel title={`${t.lists.editor} · ${taskId || t.empty}`}><p className="muted">{t.hints.jsonHelp}</p><textarea className="json-editor" value={taskEditor} onChange={e=>setTaskEditor(e.target.value)}/><div className="actions"><button onClick={saveTask}><Save size={14}/>{t.save}</button><button onClick={deleteTask} disabled={!taskId}><XCircle size={14}/>{t.remove}</button></div></Panel></div><Panel title={scheduleArtifactTitle || 'sche_tasks/done'}><div className="report-list">{(schedule.done_recent || []).map(r=><button key={r.path} onClick={()=>readScheduleArtifact(r.path)}>{r.name}<small>{new Date(r.mod_time).toLocaleString()}</small></button>)}</div><pre className="artifact-view">{scheduleArtifact || t.empty}</pre></Panel></section>}
      {tab==='models' && <Models t={t} profiles={profiles} setProfiles={setProfiles} patchProfile={patchProfile} importModels={importModels} previewModels={previewModels} saveModels={saveModels} modelPreview={modelPreview}/>} 
      {tab==='logs' && <section><div className="workspace"><Panel title={t.lists.processes}><div className="toolbar"><label>{t.hints.tailLines}<input type="number" value={tailLines} onChange={e=>setTailLines(Number(e.target.value))}/></label><button disabled={!selected} onClick={()=>loadServiceLogs(selected)}><RefreshCw size={14}/>{t.refresh}</button><button disabled={!selected || services.find(s=>s.name===selected)?.running} onClick={()=>serviceAction(selected,'start')}><Play size={14}/>{t.start}</button><button disabled={!selected || !services.find(s=>s.name===selected)?.running} onClick={()=>serviceAction(selected,'stop')}><Square size={14}/>{t.stop}</button></div>{services.map(s => <button className={selected===s.name?'select active':'select'} key={s.name} onClick={()=>loadServiceLogs(s.name)}>{s.running?'🟢':'⚪'} {s.name}<small>{s.kind}</small></button>)}</Panel><Panel title={`Logs · ${selected || '-'}`} className="log-panel">{selected && <p className="muted">{services.find(s=>s.name===selected)?.command?.join(' ')}</p>}<pre>{logs.join('\n') || t.hints.noLogs}</pre></Panel></div></section>}
    </main>
  </div>
}

function ChatPage({ t }) {
  const [sessions, setSessions] = useState([]), [sid, setSid] = useState(''), [messages, setMessages] = useState([])
  const [prompt, setPrompt] = useState(''), [busy, setBusy] = useState(false), [err, setErr] = useState('')
  const loadSessions = async () => { const d = await api('/api/chat/sessions'); setSessions(d.sessions || []); if (!sid && d.sessions?.[0]) await openSession(d.sessions[0].id) }
  const openSession = async (id) => { const d = await api(`/api/chat/session/${id}`); setSid(d.id); setMessages(d.messages || []) }
  const newSession = async () => { const d = await api('/api/chat/session/new', { method:'POST', body:'{}' }); setSid(d.id); setMessages([]); await loadSessions() }
  useEffect(()=>{ loadSessions().catch(e=>setErr(e.message)) }, [])
  const send = async () => {
    if (!prompt.trim() || busy) return
    let cur = sid
    if (!cur) { const d = await api('/api/chat/session/new', { method:'POST', body:'{}' }); cur = d.id; setSid(cur) }
    const text = prompt; setPrompt(''); setBusy(true); setErr('')
    const user = { id: `u-${Date.now()}`, role:'user', content:text, created_at: Math.floor(Date.now()/1000) }
    const assistant = { id: `a-${Date.now()}`, role:'assistant', content:'', created_at: Math.floor(Date.now()/1000) }
    setMessages(ms => [...ms, user, assistant])
    try {
      const res = await fetch(`/api/chat/${cur}`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ prompt:text, client_user_id:user.id }) })
      if (!res.ok) throw new Error(await res.text())
      const reader = res.body.getReader(), dec = new TextDecoder(); let buf = '', content = ''
      while (true) {
        const {value, done} = await reader.read(); if (done) break
        buf += dec.decode(value, {stream:true}); const lines = buf.split('\n'); buf = lines.pop() || ''
        for (const line of lines) { if (!line.trim()) continue; const ev = JSON.parse(line)
          if (ev.type === 'delta') { content += ev.delta || ''; setMessages(ms => ms.map(m => m.id === assistant.id ? {...m, content} : m)) }
          if ((ev.type === 'done' || ev.type === 'error') && ev.message) { setMessages(ms => ms.map(m => m.id === assistant.id ? ev.message : m)); if (ev.type === 'error') setErr(ev.message.content || 'error') }
        }
      }
      await loadSessions()
    } catch(e) { setErr(e.message); setMessages(ms => ms.map(m => m.id === assistant.id ? {...m, content:`失败：${e.message}`, error:true} : m)) }
    finally { setBusy(false) }
  }
  return <section className="chat-shell native-chat"><div className="chat-top"><div><h3>{t.nav.chat}</h3><p>Admin 原生对话：由 Go API 管理会话，按需启动 Python GA Worker。</p></div><div className="actions"><button onClick={loadSessions}><RefreshCw size={14}/>{t.refresh}</button><button onClick={newSession}><Play size={14}/>新会话</button><span className="ok">Native</span></div></div>{err && <div className="message">{err}</div>}<div className="chat-grid"><aside className="chat-sessions"><button className="primary" onClick={newSession}>+ 新会话</button>{sessions.map(s => <button key={s.id} className={s.id===sid?'active':''} onClick={()=>openSession(s.id)}><b>{s.title || '新会话'}</b><small>{s.count || 0} 条</small></button>)}</aside><main className="chat-main"><div className="chat-messages">{messages.length===0 && <div className="empty-chat">选择或创建会话后开始对话</div>}{messages.map(m => <div key={m.id} className={`bubble ${m.role} ${m.error?'error':''}`}><div className="role">{m.role}</div><div className="content">{m.content}</div></div>)}</div><div className="chat-compose"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{ if(e.key==='Enter' && e.ctrlKey) send() }} placeholder="输入给 GenericAgent 的任务，Ctrl+Enter 发送"/><button disabled={busy || !prompt.trim()} onClick={send}>{busy?'执行中...':'发送'}</button></div></main></div></section>
}

function TaskRow({ task, t, onToggle, onEdit, onArtifact }) { return <div className={`task-row status-${(task.status||'').toLowerCase()}`}><div><b>{task.id}</b><span>{task.schedule} · {task.repeat} · {task.status}</span>{task.error && <em className="err-text">{task.error}</em>}{task.next_hint && <em>{task.next_hint}</em>}<p>{task.prompt}</p>{task.recent_reports?.length > 0 && <div className="mini-reports">{task.recent_reports.map(r=><button key={r.path} onClick={()=>onArtifact(r.path)}>{r.name}</button>)}</div>}</div><div className="actions"><button onClick={()=>onEdit(task.id)}><Eye size={14}/>{t.read}</button><button onClick={()=>onToggle(task.id, !task.enabled)}>{task.enabled ? t.disabled : t.enabled}</button></div></div> }
function Models({ t, profiles, setProfiles, patchProfile, importModels, previewModels, saveModels, modelPreview }) { return <section><div className="model-top"><div><h3>{t.nav.models}</h3><p>{t.hints.previewHelp}</p></div><div className="actions"><button onClick={importModels}><RefreshCw size={14}/>{t.hints.modelSource}</button><button onClick={() => setProfiles([...profiles, emptyProfile(profiles.length)])}>{t.hints.addProfile}</button><button onClick={previewModels}><Eye size={14}/>{t.hints.preview}</button><button onClick={saveModels}><UploadCloud size={14}/>{t.hints.writeMykey}</button></div></div><div className="models-layout"><div className="profiles">{profiles.map((p, idx) => <div className="profile" key={idx}><div className="profile-head"><b>#{idx + 1} {p.name || p.var_name}</b><label><input type="checkbox" checked={!!p.enabled} onChange={(e) => patchProfile(idx, { enabled: e.target.checked })}/> enabled</label></div><div className="form-grid"><label>{t.fields.varName}<input value={p.var_name || ''} onChange={(e) => patchProfile(idx, { var_name: e.target.value })}/></label><label>{t.fields.type}<input value={p.type || ''} onChange={(e) => patchProfile(idx, { type: e.target.value })}/></label><label>{t.fields.name}<input value={p.name || ''} onChange={(e) => patchProfile(idx, { name: e.target.value })}/></label><label>{t.fields.model}<input value={p.model || ''} onChange={(e) => patchProfile(idx, { model: e.target.value })}/></label><label className="span2">{t.fields.apiBase}<input value={p.apibase || ''} onChange={(e) => patchProfile(idx, { apibase: e.target.value })}/></label><label className="span2">{t.fields.apiKey}<SecretInput value={p.apikey} onChange={(v) => patchProfile(idx, { apikey: v })} t={t}/></label><label>{t.fields.stream}<select value={String(!!p.stream)} onChange={(e) => patchProfile(idx, { stream: e.target.value === 'true' })}><option value="true">true</option><option value="false">false</option></select></label><label>{t.fields.maxRetries}<input type="number" value={p.max_retries ?? 3} onChange={(e) => patchProfile(idx, { max_retries: Number(e.target.value) })}/></label><label>{t.fields.readTimeout}<input type="number" value={p.read_timeout ?? 300} onChange={(e) => patchProfile(idx, { read_timeout: Number(e.target.value) })}/></label><label>{t.fields.reasoningEffort}<input value={p.reasoning_effort || ''} onChange={(e) => patchProfile(idx, { reasoning_effort: e.target.value })}/></label></div></div>)}</div><Panel title={t.lists.generatedPreview} className="preview"><pre>{modelPreview || t.empty}</pre></Panel></div></section> }
function icon(n) { const m = { overview:<Activity size={16}/>, chat:<MessageSquare size={16}/>, control:<ShieldAlert size={16}/>, files:<FileCode2 size={16}/>, tasks:<Terminal size={16}/>, memory:<Brain size={16}/>, channels:<Globe2 size={16}/>, autonomous:<Bot size={16}/>, schedule:<CalendarClock size={16}/>, models:<SlidersHorizontal size={16}/>, logs:<FolderCog size={16}/> }; return m[n] }
